spring:
  application:
    name: worker
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      enable-auto-commit: true  # Auto commit offsets
      properties:
        max.partition.fetch.bytes: 10485760
      group-id: pedidos-worker
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: ""
      timeout: 6000ms
    mongodb:
      uri: mongodb://admin:password@localhost:27017/mydatabase?authSource=admin


#custom configuration
custom:
  kafka:
    consumer:
      pedidos:
        topic:
          name: pedidos