version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
  cliente:
    build:
      context: ../go/clientes
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      ADDR_CLIENTES: "0.0.0.0:8080"
  productos:
    build:
      context: ../go/productos
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    environment:
      ADDR_CLIENTES: "0.0.0.0:8080"


